<!DOCTYPE html>
<html lang="br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Teste RH - SCUP">
        <meta name="author" content="Eric Lemes">
        <link rel="icon" href="images/favicon.ico">
        <title>Teste - SCUP</title>
        <!-- Bootstrap core CSS -->
        <link href="bootstrap-3.3.2/css/bootstrap.min.css" rel="stylesheet">
        <link href="css/base.css" rel="stylesheet">
        <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
        <!--[if lt IE 9]><script src="bootstrap-3.3.2/js/ie8-responsive-file-warning.js"></script><![endif]-->
        <script src="bootstrap-3.3.2/js/ie-emulation-modes-warning.js"></script>
    </head>
    <body>

        <!-- Menu navbar -->
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="#" onclick="link('index/principal')">
                        <img class="logo" src="images/scup-logo-orange.svg" width="100" height="30"/>
                    </a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="#" onclick="link('index/principal')">Home</a></li>
                        <li><a href="#" onclick="link('falemais')">FaleMais</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <!-- Div conteudo load-->
        <div class="container" id="conteudo">
        </div>

        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script src="bootstrap-3.3.2/js/bootstrap.min.js"></script>
        <script src="js/script.js"></script>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="bootstrap-3.3.2/js/ie10-viewport-bug-workaround.js"></script>
    </body>
</html>