<h1>Novo produto FaleMais <span class="label label-info"><img class="logo" src="images/scup-logo-orange.svg" width="95" height="20"/></span></h1>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2 col-md-offset-0" style="text-align: center;" onclick="link('falemais')">
            <div  class="form-pg">
                <b>FaleMais</b> 30 (30 minutos)
            </div>
        </div>
        <div class="col-md-2 col-md-offset-2" style="text-align: center;" onclick="link('falemais')">
            <div  class="form-pg">
                <b>FaleMais</b> 60 (60 minutos)
            </div>
        </div>
        <div class="col-md-2 col-md-offset-2" style="text-align: center;" onclick="link('falemais')">
            <div  class="form-pg">
                <b>FaleMais</b> 120 (120 minutos)
            </div>
        </div>
    </div>

    <p class="rodape-pg">
        <br>
        Com o novo produto FaleMais da ScupTel o cliente adquire um plano e pode falar de graça 
        até um determinado tempo (em minutos) e só paga os minutos excedentes. 
        Os minutos excedentes tem um acrescimo de 10% sobre a tarifa normal do minuto.
        Os planos são FaleMais 30 (30 minutos), FaleMais 60 (60 minutos) e FaleMais 120 (120 minutos).
        <a href="#SIMULAR" onclick="link('falemais/index/')">Simule agora</a></p>
</div>

</div>